#!/bin/sh
#
# chkconfig: - 88 10
# description: Start/Stop the RADICALE server daemon
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
#

# Source function library.
. /etc/rc.d/init.d/functions

SCRIPT=/usr/bin/radicale
CONFIG=/etc/radicale/config
prog=radicale
user=radicale
exec="$SCRIPT -C $CONFIG"

lockfile=/var/lock/subsys/$prog
pidfile=/var/run/$prog/$prog.pid

[ -f $SCRIPT ] || exit 0
[ -f $CONFIG ] || exit 0
 
RETVAL=0

case "$1" in
 start)
       echo -n $"Starting $prog  server: "
    daemon --user=$user --pidfile=$pidfile $exec >/dev/null 2>&1 
    status radicale
    RETVAL=$?
    [ $RETVAL -eq 0 ] && touch $lockfile
    ln -s $pidfile /var/run/$prog.pid 2>/dev/null
       ;;
 stop)
       echo -n $"Stopping $prog server: "
       killproc $SCRIPT
       RETVAL=$?
       echo
       [ $RETVAL -eq 0 ] && rm -f $lockfile
       ;;
 status)
       status radicale
       RETVAL=$?
       ;;
 restart)
       $0 stop
       sleep 3
       $0 start
       RETVAL=$?
       ;;
 *)
       echo $"Usage: $0 {start|stop|status|restart}"
       exit 1
esac

exit $RETVAL
